name = "Rete"
uuid = "3d46c559-9b3d-4aba-9ca1-48ff7627231e"
authors = ["MarkNahabedian <naha@mit.edu> and contributors"]
version = "1.0.0-DEV"

[deps]
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"

[compat]
MacroTools = "0.5"
OrderedCollections = "1.6"
julia = ">=1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
